[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"

  testImplementation "org.junit.jupiter:junit-jupiter-api:5.10.2"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.10.2"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.10.2"

  testImplementation "org.mockito:mockito-core:5.12.0"
  testImplementation "org.mockito:mockito-junit-jupiter:5.12.0"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

test {
  useJUnitPlatform()
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
